---
openapi: 3.0.1
info:
  title: Api::BookLibrary
  version: v1
components:
  schemas:
    book:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        genre:
          type: string
        publication_year:
          type: string
      required:
      - title
      - author
      - genre
      - publication_year
paths:
  "/api/books":
    get:
      summary: Return a list of books
      tags:
      - Books
      description: Endpoint used by the team to retrieve books
      parameters:
      - name: title
        in: query
        required: false
        schema:
          type: string
      - name: author
        in: query
        required: false
        schema:
          type: string
      - name: genre
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Return a list of books
          content:
            application/json:
              examples:
                test_example:
                  value:
                    books: []
    post:
      summary: Create a new book
      tags:
      - Books
      description: Endpoint used by the team to create a new book
      parameters: []
      responses:
        '200':
          description: Successfully create a book
          content:
            application/json:
              examples:
                test_example:
                  value:
                    book:
                      id: 1
                      title: Ring of Bright Water
                      author: Guillermo Nikolaus
                      genre: Mythopoeia
                      publication_year: '1916'
                      created_at: '2023-09-23T16:03:26.961Z'
                      updated_at: '2023-09-23T16:03:26.961Z'
        '422':
          description: Return error with invalid parameters
          content:
            application/json:
              examples:
                test_example:
                  value:
                    error:
                      title:
                      - can't be blank
                      - is too short (minimum is 2 characters)
                      author:
                      - can't be blank
                      - is too short (minimum is 2 characters)
                      genre:
                      - can't be blank
                      - is too short (minimum is 2 characters)
                      publication_year:
                      - can't be blank
                      uniqueness:
                      - A Darkling Plain already been recomended before.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/book"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
