---
openapi: 3.0.1
info:
  title: Api::BookLibrary
  version: v1
components:
  schemas:
    book:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        genre:
          type: string
        publication_year:
          type: string
      required:
      - title
      - author
      - genre
      - publication_year
paths:
  "/api/books":
    get:
      summary: Successfully return a list of books
      tags:
      - Books
      description: Endpoint used by the team to retrieve books
      parameters:
      - name: title
        in: query
        required: false
        schema:
          type: string
      - name: author
        in: query
        required: false
        schema:
          type: string
      - name: genre
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Return a list of books
        '422':
          description: Return an error when passing invalid parameters
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
